name: Builds

on:
  workflow_dispatch:
    inputs:
      linux:
        default: false
        type: boolean
      macos:
        default: false
        type: boolean
      windows:
        default: false
        type: boolean
      python:
        description: Python version
        default: '3.10'
        type: choice
        options:
          - '["3.10"]'
          - '["3.11"]'
          - '["3.12"]'
          - '["3.13"]'
          - '["3.14"]'

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  linux:
    if: inputs.linux
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(inputs.python) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
      - name: Build
        continue-on-error: False
        run: |
          python ruxx/release
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-${{ github.job }}-${{ matrix.python-version }}
          path: |
            release/Ruxx
            release/Ruxx.tar.gz
          compression-level: 0

  macos:
    if: inputs.macos
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        python-version: ${{ fromJSON(inputs.python) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
      - name: Build
        continue-on-error: False
        run: |
          python ruxx/release
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-${{ github.job }}-${{ matrix.python-version }}
          path: |
            release/Ruxx
            release/Ruxx.tar.gz
          compression-level: 0

  windows:
    if: inputs.windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ${{ fromJSON(inputs.python) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
      - name: Build
        continue-on-error: False
        run: |
          python ruxx/release
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-${{ github.job }}-${{ matrix.python-version }}
          path: |
            release/Ruxx.exe
            release/Ruxx.zip
          compression-level: 0
